### ISSUE TITLE
error while importing pypath 

### ISSUE THREAD

**Issue by gabora** [saezlab/pypath#109]
import pypath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/admin/.local/lib/python2.7/site-packages/pypath/__init__.py", line 26, in <module>
    import pypath.main as main
  File "/Users/admin/.local/lib/python2.7/site-packages/pypath/main.py", line 85, in <module>
    import pypath.logn as logn
AttributeError: 'module' object has no attribute 'logn'

**Comment by deeenes** [comment]
Hi,

Are you sure you are using the most recent version? We gave a completely new logging system to `pypath` a few months ago and we removed the `pypath.logn` module.

Best,

Denes

**Comment by gabora** [comment]
problem was solved by directly installing from Github. Hopefully, other users will read the instructions :)
