### ISSUE TITLE
error from loading resources: reaction_misc

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#129]
**Describe the bug**
can not load reaction_misc

**To Reproduce**
0. import pypath.resources.network as network_resources
1. pa=main.PyPath()
2. pa.load_resources(network_resources.reaction_misc,exclude=exc_name)

**Desktop (please complete the following information):**
- Python version: 3.6.7
- PyPath: 0.9.6

**Additional context**
>>> pa.load_resources(network_resources.reaction_misc,exclude=exc_name)

        Processing Reactome requires huge memory.
        Please hit `y` if you have at least 2G free memory,
        or `n` to omit Reactome.
        After processing once, it will be saved in
        /home/luli7/.pypath/cache/reactome.edges.pickle, so next time can be loaded quickly.

        Process Reactome now? [y/n]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/main.py", line 6592, in load_resources
    keep_raw = keep_raw,
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/main.py", line 6662, in load_resource
    keep_raw = keep_raw,
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/main.py", line 2553, in _read_network_data
    answer = raw_input().lower()
NameError: name 'raw_input' is not defined

**Comment by deeenes** [comment]
Fixed in 14d85be
