### ISSUE TITLE
Minimal working example not working

### ISSUE THREAD

**Issue by numpde** [saezlab/pypath#149]
**Describe the bug**
```
from pypath.core.network import Network
Network.omnipath()
```
doesn't go through. This is the most up-to-date example I [could find](https://omnipathdb.org/#tutorial).

**To Reproduce**
1. Install from git
2. run the above example

**Expected behavior**
Not sure.

**Traceback**
[2020-09-04 07:34:58] [pypath] 
	- session ID: `8mdid`
	- working directory: `/home/ra/repos/cbb/20200902-Pypath/a_firstlook`
	- logfile: `/home/ra/repos/cbb/20200902-Pypath/a_firstlook/pypath_log/pypath-8mdid.log`
	- pypath version: 0.11.30
Traceback (most recent call last):
  File "/home/ra/repos/cbb/20200902-Pypath/a_firstlook/firstlook.py", line 11, in <module>
    op = Network.omnipath()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 2995, in omnipath
    new.load_omnipath(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 2769, in load_omnipath
    self.load(omnipath, exclude = exclude)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 602, in load
    self.load_resource(resource, **kwargs)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 666, in load_resource
    self._read_resource(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 1274, in _read_resource
    edge_list_mapped = self._map_list(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 1539, in _map_list
    list_mapped += self._map_edge(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 1600, in _map_edge
    default_id_a = mapping.map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 2484, in map_name
    return mapper.map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1632, in map_name
    mapped_names = self.uniprot_cleanup(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1649, in uniprot_cleanup
    uniprots = self.primary_uniprot(uniprots)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1934, in primary_uniprot
    primary = self.map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1449, in map_name
    mapped_names = self._map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1780, in _map_name
    tbl = self.which_table(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1131, in which_table
    self.load_mapping(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 2199, in load_mapping
    reader = MapReader(param = resource, **kwargs)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 170, in __init__
    self.load()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 200, in load
    self.read()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 346, in read
    getattr(self, method)()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 454, in read_mapping_file
    for i, line in enumerate(infile):
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 454, in get_uniprot_sec
    proteome = all_uniprots(organism=organism)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 78, in all_uniprots
    return get_db(organism = organism, swissprot = swissprot)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 118, in get_db
    init_db(organism = organism, swissprot = swissprot)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 104, in init_db
    globals()['db'][key] = _all_uniprots(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 72, in _all_uniprots
    l.strip() for l in data.split('\n')[1:] if l.strip()
AttributeError: 'NoneType' object has no attribute 'split'

Process finished with exit code 1

**Log file**
--
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Python version: Python 3.8.2
 - Version or commit hash: pypath @ git+https://github.com/saezlab/pypath.git@504947c04163e00a0bb23449e81680a69fe35481

**Additional context**
I'd like to start using pypath.

**Comment by numpde** [comment]
Btw., if I understand correctly: `/dist` is in the `.gitignore` file, which is at odds with the installation instructions.

**Comment by Nic-Nic** [comment]
Dear Dear @numpde 
I was not able to find the commit hash you mention in your bug report.
I tried to reproduce your error with the latest version of pypath and works just fine.
I remember seeing this error before and usually this happens because of a corrupted file in the cache.
You can try to clear the cache (by default in `~/.pypath`) or load the `Network` inside the context of `pypath.share.curl.cache_off()` like:
```
from pypath.core import network
from pypath.share import curl

with curl.cache_off():
    opath = network.Network.omnipath()
```

**Comment by numpde** [comment]
Thank you for the response. This does *not* raise the error:
o) Your example with `curl.cache_off`; 
o) the original example after deleting `~/.pypath`; 
o) the original example repeated after aborted download and w/o deleting `~/.pypath`. 

(I wish there was some progress indication in `Network.omnipath()`. I see network traffic in the system monitor but have no idea how long it'll take. What exactly is "vast amount of data download"? Being on the move, I haven't been able to do this step for several days now.)

About the non-existing hash, I don't know: the line is verbatim from `pip freeze`.

**Comment by deeenes** [comment]
That's great, so @Nic-Nic was right, likely it was due to a download failure.

Some time ago we had progress bars, some of them disappeared unnoticed as they are disabled by default, I will restore those. Actually if you do this you should have progress bars at downloads:
```
from pypath.share import settings
settings.setup(progressbars = True)
```

If you are still experiencing any error, it would be key to find out which method fails and how. I would suggest to delete the last accessed cache file (see in the log) after experiencing the error. Then try again the method which failed, e.g. based on the traceback above:
```
from pypath.inputs import uniprot
u = uniprot.all_uniprots()
```
If still not good, please send us the traceback and the log.

**Comment by numpde** [comment]
After clearing the cache (`rm -rf ~/.pypath`), the code

```
from pypath.share import settings
settings.setup(progressbars = True)

from pypath.core.network import Network
op = Network.omnipath()
```

fails with the following history (and [pypath-2k0pl.log](https://github.com/saezlab/pypath/files/5180096/pypath-2k0pl.log)):

```
/home/ra/repos/cbb/venv/bin/python /home/ra/repos/cbb/20200902-Pypath/a_firstlook/firstlook.py

	=== d i s c l a i m e r ===

	All data accessed through this module,
	either as redistributed copy or downloaded using the
	programmatic interfaces included in the present module,
	are free to use at least for academic research or
	education purposes.
	Please be aware of the licenses of all the datasets
	you use in your analysis, and please give appropriate
	credits for the original sources when you publish your
	results. To find out more about data sources please
	look at `pypath.resources.descriptions` or
	http://omnipathdb.org/info and 
	`pypath.resources.urls.urls`.

[2020-09-06 20:07:12] [pypath] 
	- session ID: `2k0pl`
	- working directory: `/home/ra/repos/cbb/20200902-Pypath/a_firstlook`
	- logfile: `/home/ra/repos/cbb/20200902-Pypath/a_firstlook/pypath_log/pypath-2k0pl.log`
	- pypath version: 0.11.30
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 430kit [00:02, 165kit/s] 
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 125kit [00:01, 74.7kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 383kit [00:02, 159kit/s] 
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 166kit [00:01, 83.5kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 82.8kit [00:01, 50.9kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 100kit [00:01, 61.8kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 57.0kit [00:01, 44.1kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 97.5kit [00:01, 60.5kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 99.7kit [00:01, 60.9kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 197kit [00:02, 96.9kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 122kit [00:01, 73.1kit/s]
        Downloading `show` from www.trpchannel.org -- 0.00B downloaded: : 87.2kit [00:01, 53.4kit/s]
        Downloading `` from www.uniprot.org -- failed: : 0.00it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/ra/repos/cbb/20200902-Pypath/a_firstlook/firstlook.py", line 13, in <module>
    op = Network.omnipath()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 2995, in omnipath
    new.load_omnipath(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 2769, in load_omnipath
    self.load(omnipath, exclude = exclude)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 602, in load
    self.load_resource(resource, **kwargs)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 666, in load_resource
    self._read_resource(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 1274, in _read_resource
    edge_list_mapped = self._map_list(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 1539, in _map_list
    list_mapped += self._map_edge(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/core/network.py", line 1600, in _map_edge
    default_id_a = mapping.map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 2484, in map_name
    return mapper.map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1632, in map_name
    mapped_names = self.uniprot_cleanup(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1649, in uniprot_cleanup
    uniprots = self.primary_uniprot(uniprots)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1934, in primary_uniprot
    primary = self.map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1449, in map_name
    mapped_names = self._map_name(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1780, in _map_name
    tbl = self.which_table(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 1131, in which_table
    self.load_mapping(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 2199, in load_mapping
    reader = MapReader(param = resource, **kwargs)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 170, in __init__
    self.load()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 200, in load
    self.read()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 346, in read
    getattr(self, method)()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/utils/mapping.py", line 454, in read_mapping_file
    for i, line in enumerate(infile):
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 454, in get_uniprot_sec
    proteome = all_uniprots(organism=organism)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 78, in all_uniprots
    return get_db(organism = organism, swissprot = swissprot)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 118, in get_db
    init_db(organism = organism, swissprot = swissprot)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 104, in init_db
    globals()['db'][key] = _all_uniprots(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 72, in _all_uniprots
    l.strip() for l in data.split('\n')[1:] if l.strip()
AttributeError: 'NoneType' object has no attribute 'split'

Process finished with exit code 1

```

**Comment by deeenes** [comment]
I could not reproduce the error. You said you could run the code without error after deleting `~/.pypath` and with `cache_off`? Maybe remove `~/.pypath/cache/582ab5c0b5fffa42fb3e8d1757901ea1-`, and when you have good network connection do:
```
from pypath.inputs import uniprot
u = uniprot.all_uniprots()
```
And if it works don't delete the cache any more.

**Comment by numpde** [comment]
After removing `~/.pypath`, the code 

```
from pypath.inputs import uniprot
u = uniprot.all_uniprots()
```

fails immediately with an empty logfile and

```
/home/ra/repos/cbb/venv/bin/python /home/ra/repos/cbb/20200902-Pypath/a_firstlook/firstlook.py

	=== d i s c l a i m e r ===

	All data accessed through this module,
	either as redistributed copy or downloaded using the
	programmatic interfaces included in the present module,
	are free to use at least for academic research or
	education purposes.
	Please be aware of the licenses of all the datasets
	you use in your analysis, and please give appropriate
	credits for the original sources when you publish your
	results. To find out more about data sources please
	look at `pypath.resources.descriptions` or
	http://omnipathdb.org/info and 
	`pypath.resources.urls.urls`.

[2020-09-07 06:19:12] [pypath] 
	- session ID: `9cbx5`
	- working directory: `/home/ra/repos/cbb/20200902-Pypath/a_firstlook`
	- logfile: `/home/ra/repos/cbb/20200902-Pypath/a_firstlook/pypath_log/pypath-9cbx5.log`
	- pypath version: 0.11.30
Traceback (most recent call last):
  File "/home/ra/repos/cbb/20200902-Pypath/a_firstlook/firstlook.py", line 7, in <module>
    u = uniprot.all_uniprots()
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 78, in all_uniprots
    return get_db(organism = organism, swissprot = swissprot)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 118, in get_db
    init_db(organism = organism, swissprot = swissprot)
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 104, in init_db
    globals()['db'][key] = _all_uniprots(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/inputs/uniprot.py", line 72, in _all_uniprots
    l.strip() for l in data.split('\n')[1:] if l.strip()
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by deeenes** [comment]
That's very weird. Let's see what's exactly happening in the download: after removing `~/.pypath/cache/582ab5c0b5fffa42fb3e8d1757901ea1-`, could you please run the following, and send the log:

```
from pypath.share import curl
from pypath.inputs import uniprot

with curl.debug_on():
    u = uniprot._all_uniprots()
```

**Comment by Nic-Nic** [comment]
Not 100% sure but may be a problem on the UniProt's server side... We have this error from time to time and I also had some problems myself when interacting with the UniProt API every now and then... :thinking:

**Comment by numpde** [comment]
I ran 

```
from pypath.share import curl
from pypath.inputs import uniprot

with curl.debug_on():
    u = uniprot._all_uniprots()
```

Before clearing the cache: [pypath-9ahkf.log](https://github.com/saezlab/pypath/files/5184357/pypath-9ahkf.log)
After clearing the cache: [pypath-1vhqp.log](https://github.com/saezlab/pypath/files/5184365/pypath-1vhqp.log)

**Comment by deeenes** [comment]
From the log i think it is an SSL issue. It might worked for you a some other attempts because the load balancer of uniprot.org just by accident might have redirected your request to some other domain than ebi.ac.uk. In the log we see `TLSv1.3 (IN), TLS alert, handshake failure (552)` and `error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure` and `PycURL error: (35, 'error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure')`. I would suggest to make sure your CA certificates are up to date:
```
sudo update-ca-certificates
```
And make sure your `curl` and `pycurl` are up to date and compiled with OpenSSL support. To check this:
```
import pycurl
pycurl.version
# 'PycURL/7.43.0.3 libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0'
```

**Comment by numpde** [comment]
The command `sudo update-ca-certificates` did nothing. The failing setup was `'PycURL/7.43.0.5 libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3'`. 

After a manual pycurl update and a major system upgrade, the setup is `'PycURL/7.43.0.6 .. same'`.

The original example
```
from pypath.core.network import Network
Network.omnipath()
````
then went through (unfortunately, I don't have the console output, and github doesn't accept the logfile as an attachment here b/c "don't support that file type"). 

As a suggestion, consider proving a packaged download (e.g. a pickle file) for convenience and, perhaps more importantly, versioning/reproducibility purposes. 

Thank you for the help.

**Comment by deeenes** [comment]
Great, I am very glad it works finally. 
Indeed because pypath is a database building tool, it is highly prone to undeterministic behaviour and failures, due to its interaction with a large number of external services. Providing pickles is definitely an option what we are considering, for this we need to set up and find capacity for an automatic build system, but likely we will have it in the future.
