### ISSUE TITLE
pathway signalink3 not loading

### ISSUE THREAD

**Issue by numpde** [saezlab/pypath#152]
This example is based on legacy code but I think the issue is unrelated to that. 

Among pathway datasets 

'trip', 'spike', 'signalink3', 'guide2pharma', 'ca1', 'arn', 'nrf2', 'macrophage', 'death', 'pdz', 'signor', 'adhesome', 'icellnet', 'hpmr', 'cellphonedb', 'ramilowski2015', 'lrdb', 'baccin2019', 

only 'signalink3' is not loading.

```
from pypath.legacy.main import PyPath
pa = PyPath()

from pypath.resources import data_formats

for (k, v) in data_formats.pathway.items():
    if k.startswith("signalink"):
        pa.load_resources({k: v})
```

Output:
```
...
Traceback (most recent call last):
  File "/home/ra/repos/cbb/20200902-Pypath/a_firstlook/firstlook.py", line 28, in <module>
    if k.startswith("signalink"):
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/legacy/main.py", line 6605, in load_resources
    self.load_resource(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/legacy/main.py", line 6676, in load_resource
    self._read_network_data(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/legacy/main.py", line 2811, in _read_network_data
    this_edge_dir = self._process_direction(
  File "/home/ra/repos/cbb/venv/lib/python3.8/site-packages/pypath/legacy/main.py", line 2417, in _process_direction
    this_directed = set(line[dir_col].split(dir_sep))
AttributeError: 'bool' object has no attribute 'split'

Process finished with exit code 1

```

[pypath-r9kwq.log](https://github.com/saezlab/pypath/files/5199762/pypath-r9kwq.log)
[SLK3 cache files](https://github.com/saezlab/pypath/files/5199828/SLK3_2020_03_23.zip)

**Comment by deeenes** [comment]
Hi,

Thanks for finding this.
Fixed in 3cd77b6b

Best,

Denes
