### ISSUE TITLE
Not able to generate omnipath network

### ISSUE THREAD

**Issue by ayadlin** [saezlab/pypath#160]
The bug I described in #156 is still causing troubles.
I installed omnipath 011.37 in my windows machine, python version 3.8.3 (I need to work in windows as some external services I am using are only windows available) using:  

python -m pip install git+git://github.com/saezlab/pypath.git

Successfully built pypath-omnipath timeloop
Installing collected packages: timeloop, pyreadr, pypath-omnipath
Successfully installed pypath-omnipath-0.11.37 pyreadr-0.3.6 timeloop-1.0.2

I run python from command line

```
C:\Users\aleja>python
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypath.core import network

        === d i s c l a i m e r ===

        All data accessed through this module,
        either as redistributed copy or downloaded using the
        programmatic interfaces included in the present module,
        are free to use at least for academic research or
        education purposes.
        Please be aware of the licenses of all the datasets
        you use in your analysis, and please give appropriate
        credits for the original sources when you publish your
        results. To find out more about data sources please
        look at `src/pypath/resources/data/resources.json` or
        https://omnipathdb.org/info and
        `pypath.resources.urls.urls`.

[2020-11-13 12:36:17] [pypath]
        - session ID: `nuczi`
        - working directory: `C:\Users\aleja`
        - logfile: `C:\Users\aleja\pypath_log\pypath-nuczi.log`
        - pypath version: 0.11.37
[2020-11-13 12:36:18] [curl] Module `fabric` not available.
>>> op = network.Network.omnipath()
[2020-11-13 12:37:38] [network] `get_dip`: Could not find file or input function or failed preprocessing.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\core\network.py", line 3062, in omnipath
    new.load_omnipath(
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\core\network.py", line 2821, in load_omnipath
    self.load(omnipath, exclude = exclude)
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\core\network.py", line 604, in load
    self.load_resource(resource, **kwargs)
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\core\network.py", line 668, in load_resource
    self._read_resource(
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\core\network.py", line 1045, in _read_resource
    for lnum, line in enumerate(prg):
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\share\progress.py", line 120, in __iter__
    for it in iterable:
  File "C:\Users\aleja\anaconda3\lib\site-packages\pypath\inputs\huri.py", line 263, in _huri_interactions
    id_a, isoform_a = reuniprot.match(row[0]).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```
I know this is supposed to be fixed -  could it be an issue when again now that you moved to v011.37?

Thanks,

A

**Comment by deeenes** [comment]
Apologies for the later response. It's indeed similar to #156 but the issue was with another URL. Now I hopefully updated all of them and fixed also some other issues in the preprocessing.
