### ISSUE TITLE
[server] pandas issue with `agg({})`: ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by deeenes** [saezlab/pypath#164]
We get an error here with `pandas > 1.1.5`: https://github.com/saezlab/pypath/blob/76c54ba299b9dcd37b2a2556465ae900f09d7f84/src/pypath/omnipath/server/run.py#L1427

```
from pypath.omnipath.server import run
run.Rest(33333, serverclass = run.TableServer, only_tables = ['intercell'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/denes/Dokumentumok/omnipath2/pypath/omnipath/server/run.py", line 2831, in __init__
    self.server = serverclass(**kwargs)
  File "/home/denes/Dokumentumok/omnipath2/pypath/omnipath/server/run.py", line 1230, in __init__
    self._preprocess_intercell()
  File "/home/denes/Dokumentumok/omnipath2/pypath/omnipath/server/run.py", line 1428, in _preprocess_intercell
    self.data['intercell_summary'] = tbl.groupby(
  File "/usr/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 945, in aggregate
    result, how = aggregate(self, func, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pandas/core/aggregation.py", line 566, in aggregate
    return agg_dict_like(obj, arg, _axis), True
  File "/usr/lib/python3.9/site-packages/pandas/core/aggregation.py", line 766, in agg_dict_like
    result = concat({k: results[k] for k in keys_to_use}, axis=axis)
  File "/usr/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 285, in concat
    op = _Concatenator(
  File "/usr/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by deeenes** [comment]
Fixed in a75cc27
