### ISSUE TITLE
Cannot load network from signor

### ISSUE THREAD

**Issue by marcorusc** [saezlab/pypath#176]
**Describe the bug**
As in the title, I can't initiate a network from signor, it gives me the error: "map_name0() got an unexpected keyword argument 'expand_complexes'"

I managed to load spike, signalink3, adhesome and others, but still when loading signor I have this error.

I also had some problems loading other networks (I tried to clean my cache folder, verify the integrity etc... still I got the error: TypeError: 'NoneType' object is not iterable), the solution was switching to a different wifi connection.

**To Reproduce**
1. from pypath.core import network
2. from pypath.resources import network as netres
3. n = network.Network()
4. n.init_network({'signor': netres.data_formats.pathway['signor']})

5. map_name0() got an unexpected keyword argument 'expand_complexes'

**Expected behavior**
Loading the signor network 

**Traceback**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/core/network.py", line 609, in load
    self.load_resource(resource, **kwargs)
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/core/network.py", line 690, in load_resource
    self._add_edge_list(
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/core/network.py", line 1777, in _add_edge_list
    self._add_update_edge(
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/core/network.py", line 1899, in _add_update_edge
    entity_b = entity_mod.Entity(
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/core/entity.py", line 127, in __init__
    self.set_label()
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/core/entity.py", line 430, in set_label
    self.label = mapping.label(
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/utils/mapping.py", line 3028, in label
    return mapper.label(
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/utils/mapping.py", line 2182, in label
    elif hasattr(name, 'genesymbol_str'):
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/internals/intera.py", line 1523, in genesymbol_str
    return COMPLEX_SEP.join(self.genesymbols)
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/internals/intera.py", line 1511, in genesymbols
    return sorted(
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/internals/intera.py", line 1513, in <genexpr>
    mapping.map_name0(uniprot, 'uniprot', 'genesymbol') or
  File "/home/user/anaconda3/envs/My_env/lib/python3.9/site-packages/pypath/utils/mapping.py", line 2948, in map_name0
    return mapper.map_name0(
TypeError: map_name0() got an unexpected keyword argument 'expand_complexes'

**Log file**
[pypath-mefa2.log](https://github.com/saezlab/pypath/files/7104922/pypath-mefa2.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python version: Python 3.9.5
 - Version or commit hash: commit 4b5b011e6e2f8f45aa5d3e669ebca693502e264a

**Comment by deeenes** [comment]
Hi,

Should be fixed in 8b1abc7 sorry for the inconvenience.

Best,

Denes

**Comment by marcorusc** [comment]
Perfect I managed to download everything, thank you very much!
