### ISSUE TITLE
Exception while building pypath from source

### ISSUE THREAD

**Issue by MelihDarcanxyz** [saezlab/pypath#186]
**Describe the bug**
I can't build pypath from the source.

**To Reproduce**
1. Run "pip install git+https://github.com/saezlab/pypath.git" without quotes.

**Expected behavior**
Pypath module to be installed successfully

**Traceback**
```python
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3024, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2821, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exdeval/.local/lib/python3.10/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.10/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected string_end, found 'extra'  (at char 27), (line:1, col:28)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 348, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 208, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 199, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate=candidate):
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
    return [
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
    return [
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 251, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2742, in requires
    dm = self._dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3026, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3036, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3089, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/exdeval/.local/lib/python3.10/site-packages/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'extra =='": Expected string_end
```

**Desktop (please complete the following information):**
 - OS: Linux 5.15.50-1-lts x86_64
 - Python version: 3.10.5

**Comment by MelihDarcanxyz** [comment]
It's installed successfully, thanks. Now I'm having another issue with disgenet.py as I'm trying to develop a function for DisgeNET API. Should I open a new issue?

**Comment by deeenes** [comment]
Yes, feel free to open another issue for that.
