### ISSUE TITLE
'Literal' is not defined in pypath/omnipath/app.py:617

### ISSUE THREAD

**Issue by t-silvers** [saezlab/pypath#202]
**Describe the bug**
Importing `omnipath` from pypath hits [this line](https://github.com/saezlab/pypath/blob/49544b2a660aa5b36e8a511c72c905b7a9473b2e/pypath/omnipath/app.py#L617) and raises
```
NameError: name 'Literal' is not defined
```
because `typing.Literal` isn't imported (or w/e custom type).

**To Reproduce**
1. `pip install pypath-omnipath`
2. `$ python -c "from pypath import omnipath"`

**Traceback**
```
$ python -c "from pypath import omnipath"
[2022-11-08 12:52:36] [curl] Module `pysftp` not available. Only downloading of a small number of resources relies on this module. Please install by PIP if it is necessary for you.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/lib/python3.10/site-packages/pypath/omnipath/__init__.py", line 32, in <module>
    from pypath.omnipath import app as _app_mod
  File "/path/to/lib/python3.10/site-packages/pypath/omnipath/app.py", line 49, in <module>
    class DatabaseManager(session_mod.Logger):
  File "/path/to/lib/python3.10/site-packages/pypath/omnipath/app.py", line 617, in DatabaseManager
    module: Literal[
NameError: name 'Literal' is not defined
```
\
\
will include other info if needed. thanks for a useful package :beers:

**Comment by deeenes** [comment]
Thanks for reporting this!
