### ISSUE TITLE
Import error on `from pypath.utils import mapping`

### ISSUE THREAD

**Issue by ivirshup** [saezlab/pypath#236]
**Describe the bug**

Cannot import `mapping` utility. Potentially an upstream bug in pycurl.

**To Reproduce**

```sh
mamba create -yn pypath-test-install python=3.10
conda activate pypath-test-install
pip install pypath-omnipath
python -c "from pypath.utils import mapping"
```

**Expected behavior**

No error to be thrown.

**Traceback**
If you have a traceback please quote it in your report.

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/utils/mapping.py", line 70, in <module>
    import pypath.resources.urls as urls
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/resources/__init__.py", line 25, in <module>
    from . import controller as _controller_mod
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/resources/controller.py", line 45, in <module>
    import pypath.resources.network as netres
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/resources/network.py", line 31, in <module>
    import pypath.resources.data_formats as data_formats
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/resources/data_formats.py", line 39, in <module>
    import pypath.utils.taxonomy as taxonomy
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/utils/taxonomy.py", line 38, in <module>
    import pypath.inputs.uniprot as uniprot_input
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/inputs/uniprot.py", line 40, in <module>
    import pypath.share.curl as curl
  File "/Users/isaac/miniconda3/envs/pypath-test-install/lib/python3.10/site-packages/pypath/share/curl.py", line 49, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)
```

**Log file**
Please attach the log file or at least the last few lines of it.
This way we can see better exactly at which operation and at
processing of which dataset the error occured.

**Desktop (please complete the following information):**
 - OS: macOS 11.7.6
 - Python version: 3.10
 - Version or commit hash: 0.14.48

**Additional context**

<details>
<summary> Installed packages </summary>

```
# packages in environment at /Users/isaac/miniconda3/envs/pypath-test-install:
#
# Name                    Version                   Build  Channel
attrs                     23.1.0                   pypi_0    pypi
bcrypt                    4.0.1                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
boltons                   23.0.0                   pypi_0    pypi
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2022.12.7            h033912b_0    conda-forge
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              40.0.2                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
face                      20.1.1                   pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
glom                      23.3.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.40.0               ha978bb4_1    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
lxml                      4.9.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
ncurses                   6.3                  h96cf925_1    conda-forge
numpy                     1.24.3                   pypi_0    pypi
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.1.0                h8a1eda9_2    conda-forge
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
paramiko                  3.1.0                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1.1             pyhd8ed1ab_0    conda-forge
psutil                    5.9.5                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycurl                    7.45.2                   pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pypath-omnipath           0.14.48                  pypi_0    pypi
pyreadr                   0.4.7                    pypi_0    pypi
pysftp                    0.2.9                    pypi_0    pypi
python                    3.10.10         he7542f4_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
rdata                     0.9                      pypi_0    pypi
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.28.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlparse                  0.4.4                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
timeloop                  1.0.2                    pypi_0    pypi
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xarray                    2023.4.2                 pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xz                        5.2.6                h775f41a_0    conda-forge
```

</details>

**Comment by slobentanzer** [comment]
I just have my low-CS-background opinion to offer, but for me, reinstalling pycurl "--with-openssl" solved the problem in every case. However, I was only on Mac M1, so not sure this generalises well. I agree that this is probably not an upstream bug but a configuration issue. I would be interested what causes it, though, as I have heard this problem from several people now in connection to `pypath`, and a general solution would be desirable. It seems a default config or `curl`/`openssl` installation clashes with the way it is used by `pypath`.

It is indeed curious that your pip does not have this option.

**Comment by ivanovaos** [comment]
I experienced similar problem on my mac (old chip, not M1), in my case I was in need to install newer command line tools and relink openssl manually.

**Comment by slobentanzer** [comment]
> I think I would consider it a strong usability issue if installing pycurl into a fresh conda environment led to a broken pycurl installation

Agree; this may be a legacy issue. IIRC the pycurl functionality was implemented quite a while ago.

> I would note that this argument is also not included in [pip install's online docs](https://pip.pypa.io/en/stable/cli/pip_install/).

Maybe this is now the `--global-option`? seems to have similar (or the same?) purpose of modifying setup.py settings. The stackoverflow post I got my solution from is 2 years old after all.

**Comment by ivirshup** [comment]
Oh, it looks like `--install-option` was deprecated and has been removed https://pip.pypa.io/en/stable/news/

It seems like it could be replaced with some usage of `--config-settings`. However, while this ran, pycurl still errored import:

```
pip install --compile --config-settings="--build-option=--with-openssl" --upgrade --force-reinstall pycurl
```

**Comment by slobentanzer** [comment]
The `config-settings` usage also appears to be more somewhat of a hack than official functionality, and in any case this should not be required in a fairly default environment, so fixing this on our end probably is a better solution. Don't know how much work this is, though.

**Comment by slobentanzer** [comment]
Just replicated on my machine with conda for test purposes; I get the same issue. Here's what I did:

```
conda create -n test python=3.10
conda activate test
pip install pypath-omnipath
python -c "from pypath.utils import mapping"
```

Upon `import pycurl` I get the following error: `ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)`. My setup is pretty vanilla, so I guess it can be reasonably expected to happen to others as well.

**Comment by Nic-Nic** [comment]
Is this issue still occurring? I tried to replicate in Ubuntu 22.04 and everything works fine, could be related to iOS?
If not occurring anymore, we can close the issue.
