### ISSUE TITLE
ValueError: readline of closed file in read_mapping_file

### ISSUE THREAD

**Issue by jwindhager** [saezlab/pypath#24]
Hi

I installed the latest pypath version within a new conda environment on a Ubuntu 18.04 machine:
```
# Name                    Version                   Build    Channel
asn1crypto                0.24.0                    <pip>
beautifulsoup4            4.6.3                     <pip>
ca-certificates           2018.03.07                    0    anaconda
cairo                     1.14.12              h8948797_3    anaconda
certifi                   2018.8.24                py36_1    anaconda
cffi                      1.11.5                    <pip>
chardet                   3.0.4                     <pip>
chembl-webresource-client 0.9.31                    <pip>
configparser              3.5.0                     <pip>
cryptography              2.3.1                     <pip>
cycler                    0.10.0                    <pip>
easydict                  1.8                       <pip>
expat                     2.2.6                he6710b0_0    anaconda
fisher                    0.1.5                     <pip>
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.9.1                h8a8886c_1    anaconda
fribidi                   1.0.5                h7b6447c_0    anaconda
future                    0.16.0                    <pip>
gevent                    1.3.6                     <pip>
gevent-openssl            1.2                       <pip>
glib                      2.56.2               hd408876_0    anaconda
gmp                       6.1.2                hfc679d8_0    conda-forge
graphite2                 1.3.12               h23475e2_2    anaconda
graphviz                  2.40.1               h21bd128_2    anaconda
greenlet                  0.4.15                    <pip>
grequests                 0.2.0                     <pip>
harfbuzz                  1.8.8                hffaf4a1_0    anaconda
httplib2                  0.11.3                    <pip>
icu                       58.2                 h211956c_0    anaconda
idna                      2.7                       <pip>
igraph                    0.7.1                hcc8e21d_5    conda-forge
jpeg                      9b                   habf39ab_1    anaconda
kiwisolver                1.0.1                     <pip>
libcurl                   7.61.1               heec0ca6_0    anaconda
libffi                    3.2.1                h4deb6c0_3    anaconda
libgcc-ng                 8.2.0                hdf63c60_1    anaconda
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.34               hb9fc6fc_0    anaconda
libssh2                   1.8.0                h9cfc8f7_4    anaconda
libstdcxx-ng              8.2.0                hdf63c60_1    anaconda
libtiff                   4.0.9                he85c1e1_2    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.8                h26e45fe_1    anaconda
lxml                      4.2.5                     <pip>
matplotlib                3.0.0                     <pip>
ndg-httpsclient           0.5.1                     <pip>
openssl                   1.0.2p               h14c3975_0    anaconda
pandas                    0.23.4                    <pip>
pango                     1.42.4               h049681c_0    anaconda
patsy                     0.5.0                     <pip>
pcre                      8.42                 h439df22_0    anaconda
pip                       10.0.1                   py36_0    anaconda
pixman                    0.34.0               ha72d70b_1    anaconda
pyasn1                    0.4.4                     <pip>
pycairo                   1.17.1           py36h2a1e443_0    anaconda
pycparser                 2.19                      <pip>
pycurl                    7.43.0.2         py36hb7f436b_0    anaconda
pygraphviz                1.3              py36h14c3975_1    anaconda
pyOpenSSL                 18.0.0                    <pip>
pyparsing                 2.2.2                     <pip>
pypath                    0.7.90                    <pip>
python                    3.6.0                         0    anaconda
python-dateutil           2.7.3                     <pip>
python-igraph             0.7.1.post6      py36h470a237_5    conda-forge
pytz                      2018.5                    <pip>
readline                  6.2                           2    anaconda
requests                  2.19.1                    <pip>
requests-cache            0.4.13                    <pip>
scipy                     1.1.0                     <pip>
setuptools                40.2.0                   py36_0    anaconda
sqlite                    3.13.0                        0    anaconda
statsmodels               0.9.0                     <pip>
tk                        8.5.18                        0    anaconda
tqdm                      4.26.0                    <pip>
unittest2py3k             0.5.1                     <pip>
unittest2six              0.0.0                     <pip>
urllib3                   1.23                      <pip>
wheel                     0.31.1                   py36_0    anaconda
xlrd                      1.1.0                     <pip>
xz                        5.2.4                h14c3975_4    anaconda
zlib                      1.2.11               hfbfcf68_1    anaconda
```

Then I tried running the following code:
```
>>> import pypath
	:: No MySQL support.
	:: No MySQL support.

	:: Module `pyfstp` not available. 
        Only downloading of a small number of resources 
        relies on this module.
        Please install by PIP if it is necessary for you.
    No `fabric` available.
	:: No `bioservices` available.
	:: Module `hcluster` not available.
>>> pa = pypath.PyPath()

	=== d i s c l a i m e r ===

	All data coming with this module
	either as redistributed copy or downloaded using the
	programmatic interfaces included in the present module
	are available under public domain, are free to use at
	least for academic research or education purposes.
	Please be aware of the licences of all the datasets
	you use in your analysis, and please give appropriate
	credits for the original sources when you publish your
	results. To find out more about data sources please
	look at `pypath.descriptions` and
	`pypath.data_formats.urls`.

	> New session started,
	session ID: 'gz3n7'
	logfile: './log/gz3n7.log'
	pypath version: 0.7.90
>>> pa.load_omnipath()
	:: Loading data from cache previously downloaded from www.uniprot.org
        :: Ready. Resulted `plain text` of type unicode string.                                                                                       
	:: Local file at `/home/jonas/pypath/cache/784f0a43e5831454b1d10db1b9480df7-`.
 > TRIP
	:: Loading 'uniprot-sec' to 'uniprot-pri' mapping table
	:: Loading data from cache previously downloaded from www.uniprot.org
        :: Ready. Resulted `plain text` of type unicode string.                                                                                       
	:: Local file at `/home/jonas/pypath/cache/c87b574b25efc888967e7ab939302989-`.
        Downloading `sec_ac.txt` from ftp.uniprot.org -- 24.42MB downloaded: 100%|███████████████████████████████| 24.4M/24.4M [00:26<00:00, 859kit/s]
        :: Ready. Resulted `plain text` of type file object.                                                                                          
	:: Local file at `/home/jonas/pypath/cache/49314fe217bf0f2a5544a2c4314b4adf-sec_ac.txt`.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/main.py", line 7725, in load_omnipath
    self.load_resources(omnipath, exclude = exclude)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/main.py", line 3401, in load_resources
    redownload=redownload)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/main.py", line 3440, in load_resource
    redownload=redownload)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/main.py", line 1368, in read_data_file
    edgeListMapped = self.map_list(edgeList)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/main.py", line 1630, in map_list
    listMapped += self.map_edge(edge)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/main.py", line 1653, in map_edge
    ncbi_tax_id = edge['taxA'])
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 689, in map_name
    mappedNames = self.primary_uniprot(mappedNames)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 768, in primary_uniprot
    pr = self.map_name(u, 'uniprot-sec', 'uniprot-pri', ncbi_tax_id = 0)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 652, in map_name
    ncbi_tax_id)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 753, in _map_name
    ncbi_tax_id = ncbi_tax_id)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 530, in which_table
    ncbi_tax_id=ncbi_tax_id)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 887, in load_mappings
    cachedir=self.cachedir
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 116, in __init__
    self.read_mapping_file(param, ncbi_tax_id)
  File "/home/jonas/.conda/envs/pypath/lib/python3.6/site-packages/pypath/mapping.py", line 160, in read_mapping_file
    infile = list(toCall(**inputArgs))
ValueError: readline of closed file
```

I also tried
* using pypath 0.7.93 (latest version on GitHub),
* re-downloading the data by deleting all local pypath data directories and
* re-running the script in a new shell.

I'd appreciate any help in getting pypath to work!

**Comment by deeenes** [comment]
Hi Jonas,

It will take more than usual to fix this issue, I will be back in a few days.
Briefly, at certain resources there was a format or address change which broke the older pypath versions.
Past week I made an important change in an essential part of pypath which also broke a number of things, hence 0.7.93 expected to have quite some issues.
Btw I am also adding tests to avoid such situations in the future.

Thanks for your patience and sorry for the inconvenience.

Best,

Denes

**Comment by deeenes** [comment]
Hi Jonas,

In 0.7.94 all issues in methods called by `load_omnipath` supposed to be fixed. So this works now.
Issues affecting other methods still to be fixed and tests will be added soon.

Best wishes,

Denes
