### ISSUE TITLE
Can't import the core module

### ISSUE THREAD

**Issue by xiangpin** [saezlab/pypath#289]
**Describe the bug**

error in `from pypath.core import network`

**To Reproduce**
```
>>> import pypath
>>> from pypath.core import network
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/core/network.py", line 44, in <module>
    import pypath.core.interaction as interaction_mod
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/core/interaction.py", line 41, in <module>
    import pypath.core.evidence as pypath_evidence
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/core/evidence.py", line 38, in <module>
    import pypath.core.entity as entity
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/core/entity.py", line 34, in <module>
    import pypath.utils.mapping as mapping
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/utils/__init__.py", line 20, in <module>
    from . import orthology as homology
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/utils/orthology.py", line 45, in <module>
    import pypath.utils.mapping as mapping
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/utils/mapping.py", line 65, in <module>
    import pypath.internals.maps as maps
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/internals/maps.py", line 24, in <module>
    import pypath.internals.input_formats as input_formats
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/internals/input_formats.py", line 27, in <module>
    import pypath.inputs.uniprot as uniprot_input
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/inputs/uniprot.py", line 41, in <module>
    import pypath.utils.taxonomy as taxonomy
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/utils/taxonomy.py", line 85, in <module>
    for t in ensembl_input.ensembl_organisms()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/inputs/ensembl.py", line 46, in ensembl_organisms
    c = curl.Curl(url)
        ^^^^^^^^^^^^^^
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/share/curl.py", line 937, in __init__
    self.curl_setup()
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/share/curl.py", line 1272, in curl_setup
    self.curl_init(url = url)
  File "/biostack/tools/pyvenv/decoupler_1.6.0/lib/python3.11/site-packages/pypath/share/curl.py", line 1182, in curl_init
    self.curl.setopt(self.curl.SSL_ENABLE_ALPN, self.alpn)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: trying to obtain a non-existing attribute: SSL_ENABLE_ALPN
```
**Expected behavior**

**Traceback**
If you have a traceback please quote it in your report.

**Log file**
Please attach the log file or at least the last few lines of it.
This way we can see better exactly at which operation and at
processing of which dataset the error occured.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Python version: [e.g. 3.11]
 - Version or commit hash [e.g. v0.16.10]

**Additional context**

**Comment by deeenes** [comment]
Hello, can you please share the version of your PycURL and libcurl versions?
