### ISSUE TITLE
omnipathdb.org: 500 Internal Server Error

### ISSUE THREAD

**Issue by AtanasiuDemian** [saezlab/pypath#294]
Hi, 

It seems like the website [omnipathdb.org](https://omnipathdb.org) is down. I'm following the [tutorials](https://liana-py.readthedocs.io/en/latest/notebooks/prior_knowledge.html) from LIANA and I realized the package `omnipath` (version 1.0.8) does not work. 

```py
>> import omnipath as op

WARNING:root:Failed to download from `https://omnipathdb.org/`.
WARNING:root:Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 181, in _download
    resp.raise_for_status()
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://omnipathdb.org/queries/interactions?format=json

WARNING:root:Failed to download from `https://omnipathdb.org/`.
WARNING:root:Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 181, in _download
    resp.raise_for_status()
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://omnipathdb.org/queries/intercell?format=json
```

And the methods do not work 

```py
>> op.interactions.OmniPath().get(genesymbols = True)

WARNING:root:Failed to download from `https://omnipathdb.org/`.
WARNING:root:Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /interactions?datasets=omnipath&fields=curation_effort%2Creferences%2Csources&format=tsv&genesymbols=1 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 178, in _download
    with self._session.send(
         ^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /interactions?datasets=omnipath&fields=curation_effort%2Creferences%2Csources&format=tsv&genesymbols=1 (Caused by ResponseError('too many 500 error responses'))

WARNING:root:Failed to download from `http://no-tls.omnipathdb.org/`.
WARNING:root:Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='no-tls.omnipathdb.org', port=80): Max retries exceeded with url: /interactions?datasets=omnipath&fields=curation_effort%2Creferences%2Csources&format=tsv&genesymbols=1 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py", line 178, in _download
    with self._session.send(
         ^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='no-tls.omnipathdb.org', port=80): Max retries exceeded with url: /interactions?datasets=omnipath&fields=curation_effort%2Creferences%2Csources&format=tsv&genesymbols=1 (Caused by ResponseError('too many 500 error responses'))

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 1
----> 1 op.interactions.OmniPath().get(genesymbols = True)

File /package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/requests/_utils.py:114, in _inject_api_method.<locals>.wrapper(wrapped, _instance, args, kwargs)
    112 @wrapt.decorator(adapter=wrapt.adapter_factory(argspec_factory))
    113 def wrapper(wrapped, _instance, args, kwargs):
--> 114     return wrapped(*args, **kwargs)

File /package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/requests/_utils.py:31, in _get_helper(cls, **kwargs)
     15 @d.get_full_description(base="get")
     16 @d.get_sections(base="get", sections=["Parameters", "Returns"])
     17 def _get_helper(cls: type, **kwargs) -> pd.DataFrame:
     18     """
     19     Perform a request to the [OmniPath]_ web service.
     20 
   (...)
     29         The result which depends the type of the request and the supplied parameters.
     30     """
---> 31     return cls()._get(**kwargs)

File /package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/requests/_request.py:112, in OmnipathRequestABC._get(self, **kwargs)
    109 kwargs = self._finalize_params(kwargs)
    110 self._last_param["final"] = kwargs.copy()
--> 112 res = self._downloader.maybe_download(
    113     self._query_type.endpoint,
    114     params=kwargs,
    115     callback=callback,
    116 )
    118 if self._downloader._options.convert_dtypes:
    119     res = self._convert_dtypes(res)

File /package/python-cbrg/current/3.11/lib/python3.11/site-packages/omnipath/_core/downloader/_downloader.py:157, in Downloader.maybe_download(self, url, callback, params, cache, is_final, **_)
    154     break
    156 if res is None:
--> 157     raise
    159 return res

RuntimeError: No active exception to reraise
```

Is it still valid to use the `omnipath` package (if the website is brought back up)? 

As I can see, it's possible to call omnipath from `pypath`, but the [documentation](https://pypath.omnipathdb.org/index.html) is different. E.g. in Liana tutorial the protein-protein interactions are obtained from omnipath via `op.interactions.OmniPath().get(genesymbols = True)`, what's the equivalent command in using `pypath.omnipath`?

**Comment by deeenes** [comment]
Hello, Apologies for the late answer! The `omnipath` module is the client for our web service, and is [a different package](https://github.com/saezlab/omnipath). The web service suffers outages time to time, in these situation it returns HTTP 500, however, these situations are solved typically within a day or few hours. Let me know if you still experience any issue, I'm closing this one for now.
