### ISSUE TITLE
Problem with import pypath

### ISSUE THREAD

**Issue by ucsdwxu** [saezlab/pypath#66]
Hi, 
I am trying to issue "import pypath" but got the following error message, however I checked that the cairo module has been already installed. Any suggestion how I can solve the problem? Many thanks.

:: Module `cairo` not available.
	   Some plotting functionalities won't be accessible.
	:: Module `pygraphviz` not available.
	   You don't need it unless you want to export dot files.
	:: No MySQL support.
	:: No MySQL support.

	:: Module `pysftp` not available. 
        Only downloading of a small number of resources 
        relies on this module.
        Please install by PIP if it is necessary for you.
    	:: Module `fabric` not available.
	:: Module `bioservices` not available.
No module `cairo` available.
Some plotting functionalities won't be accessible.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/pypath/__init__.py", line 27, in <module>
    import pypath.main as main
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/pypath/main.py", line 104, in <module>
    import pypath.plot as plot
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/pypath/plot.py", line 40, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

**Comment by deeenes** [comment]
Hi,

You can test easily if `pycairo` is installed:

`import cairo`

If you have installed it but still not available check if its path is in `sys.path`:

```import sys
print(sys.path)```

You probably know where your Python distribution is located on your computer, for example on a typical Linux system you will find your distributor packaged `pycairo` here:

```/usr/lib/python3.7/site-packages/cairo/```

If you still don't find solution, please tell me what is your operating system, how you installed Python and how you installed pycairo.

I hope it helps.

Best wishes,

Denes

**Comment by deeenes** [comment]
I see you use Anaconda. Your pycairo supposed to be here: `/home/weijun/anaconda3/lib/python3.7/site-packages/cairo/`

Looking at this: https://anaconda.org/conda-forge/pycairo I think you can install it by:

`/home/weijun/anaconda3/bin/conda install -c conda-forge pycairo`

**Comment by ucsdwxu** [comment]
> I see you use Anaconda. Your pycairo supposed to be here: `/home/weijun/anaconda3/lib/python3.7/site-packages/cairo/`
> 
> Looking at this: https://anaconda.org/conda-forge/pycairo I think you can install it by:
> 
> `/home/weijun/anaconda3/bin/conda install -c conda-forge pycairo`

Hi Denes,

Thanks for guiding. I will test on it and see how it goes and let you know.

Cheers,
Weijun

**Comment by ucsdwxu** [comment]
Hi Denes,

I tried /home/weijun/anaconda3/bin/conda install -c conda-forge pycairo and it looked ok, but when I tried import pypath, some new line of error came out as shown below - the last line of the message. 
Cheers,
Weijun


:: Module `cairo` not available.
	   Some plotting functionalities won't be accessible.
	:: Module `pygraphviz` not available.
	   You don't need it unless you want to export dot files.
	:: No MySQL support.
	:: No MySQL support.

	:: Module `pysftp` not available. 
        Only downloading of a small number of resources 
        relies on this module.
        Please install by PIP if it is necessary for you.
    	:: Module `fabric` not available.
	:: Module `bioservices` not available.
No module `cairo` available.
Some plotting functionalities won't be accessible.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/pypath/__init__.py", line 27, in <module>
    import pypath.main as main
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/pypath/main.py", line 104, in <module>
    import pypath.plot as plot
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/pypath/plot.py", line 40, in <module>
    import cairo
  File "/home/weijun/anaconda3/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/weijun/anaconda3/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_xcb_surface_set_size

**Comment by ucsdwxu** [comment]
> Hi Weijun,
> 
> The symbol `cairo_xcb_set_size` should be defined in `libcairo`.
> You can check which `libcairo` your `pycairo` gets linked to. At me it looks like:
> 
> ```
> ldd -r /usr/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so | grep cairo
> libcairo.so.2 => /usr/lib/libcairo.so.2 (0x000063b9d6d38000)
> ```
> Then you can see the `cairo_xcb_set_size` is undefined in `_cairo.cpython-37m-x86_64-linux-gnu.so`:
> 
> ```
> readelf -Ws /usr/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so | grep set_size
>    279: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND cairo_ps_surface_set_size
>    344: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND cairo_pdf_surface_set_size
>    369: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND cairo_xcb_surface_set_size
> ```
> It is from `libcairo.so.2`:
> 
> ```
> readelf -Ws /usr/lib/libcairo.so.2 | grep set_size
>    391: 00000000000cc670   428 FUNC    GLOBAL DEFAULT    9 cairo_ps_surface_set_size
>    650: 00000000000aef40   161 FUNC    GLOBAL DEFAULT    9 cairo_xcb_surface_set_size
>    713: 00000000000d9000   162 FUNC    GLOBAL DEFAULT    9 cairo_pdf_surface_set_size
>    750: 00000000000a6fc0   209 FUNC    GLOBAL DEFAULT    9 cairo_xlib_surface_set_size
> ```
> I think you need to find out where your libcairo coming from and either install an other pycairo conda package or an other libcairo. E.g. I would assume the one from conda-forge should be compatible as it is from the same source:
> 
> ```
> https://anaconda.org/conda-forge/cairo
> # or there is an other one:
> https://anaconda.org/anaconda/cairo
> ```
> Best,
> 
> Denes

Hey Denes,

I think it's now working at my side. Thanks so much for your instructions. Really appreciated.

Have a nice day.

Cheers,
Weijun
