### ISSUE TITLE
GO annotation loading error

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#93]
Hi Everyone,

I am trying to load GOAnnotation and get the following errors.
I am using pypath 0.8.18, under python3.6 with Ubuntu18.04

>>> goa=go.GOAnnotation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/go.py", line 353, in __init__
    self.ontology = ontology or GeneOntology()
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/go.py", line 64, in __init__
    self._load()
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/go.py", line 79, in _load
    self._load_terms()
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/go.py", line 90, in _load_terms
    self._terms = dataio.go_terms_quickgo()
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/dataio.py", line 4459, in go_terms_quickgo
    this_result = json.loads(c.result)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thank you for your help.
Best regards
Lu

**Comment by deeenes** [comment]
Not sure but most likely this means an empty file due to a failed download. To address such errors, I added a some lines to the `curl` module to check if the cache file is empty and re-download: d051a2c
It's not tested yet and I need to set up various methods to handle download errors.

**Comment by deeenes** [comment]
Fixed, see #92
